"""
Setup file for creating distributions
"""
from setuptools import setup

setup(
    name='vqlmanager',
    version='0.1.dev0',
    packages=['venv.lib.python3.6.site-packages.PyQt5', 'venv.lib.python3.6.site-packages.PyQt5.uic',
              'venv.lib.python3.6.site-packages.PyQt5.uic.Loader', 'venv.lib.python3.6.site-packages.PyQt5.uic.port_v2',
              'venv.lib.python3.6.site-packages.PyQt5.uic.port_v3',
              'venv.lib.python3.6.site-packages.PyQt5.uic.Compiler', 'venv.lib.python3.6.site-packages.qdarkstyle',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations',
              'vqlmanager',
              'vqlmanager.images'],
    url='https://github.com/andretreebus/vqlmanager',
    license=open('LICENCE.txt').read(),
    author='Andre Treebus',
    author_email='andretreebus@hotmail.com',
    description=open('README.md').read(),
    classifiers=[
        'Development Status :: 0.1 - Beta',
        'Environment :: Console',
        'Environment :: Web Environment',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Denodo Administrators',
        'License :: OSI Approved :: Apache Software Licence Version 2',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Programming Language :: Python',
        'Topic :: Communications :: Email',
        'Topic :: Office/Business',
        'Topic :: Software Development :: Bug Tracking',
    ],
)

# bash -cl "/venv/bin/python /setup.py bdist_wininst --bdist-dir=/tmp --dist-dir=/build --bitmap=/vqlmanager/images/splitter.png --title="VQL Manager" --user-access-control=auto"
